services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/backend_db
      - SPRING_DATASOURCE_USERNAME=backend_user
      - SPRING_DATASOURCE_PASSWORD=backend_pass
    depends_on:
      - mysql
    networks:
      - backend-network

  mysql:
    image: 'mysql:8.0'
    environment:
      - 'MYSQL_DATABASE=backend_db'
      - 'MYSQL_USER=backend_user'
      - 'MYSQL_PASSWORD=backend_pass'
      - 'MYSQL_ROOT_PASSWORD=root_password'
    ports:
      - '5050:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend-network

volumes:
  mysql_data:

networks:
  backend-network:
    driver: bridge
